### ISSUE TITLE
Display of Resources within a Classification Term does not respect classification_rlshp.aspace_relationship_position

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1383] opened 2018-10-19 19:00 UTC
I've been noticing some inconsistencies with the order of Resources within a Classification or Classification Term. It's possible to define an order for the resources associated with a particular classification or classification term, but this order does not change how resources are displayed across all classification views.

## Expected Behavior

In the API, it's possible to order the resources by changing the order of the `ref` objects in the `linked_records` array of the `classification_term` JSON model. Changing the order of this array affects the `aspace_relationship_position` column of the of the `classification_rlshp` table.

You can also change the order of these resources (i.e. the aspace_relationship_position for those records) using the Staff interface.

I was expecting this order to be reflected in the Staff and PUI interfaces.

## Current Behavior

[Screenshots and Logs on Dropbox](https://www.dropbox.com/sh/hnhl9gtdjni0siv/AADzn6bThjO9SMxrQPDFte9ka?dl=0)

I've uploaded some screenshots and logs to Dropbox to show what I'm seeing on my end. It looks like the search functionality is used to display the Resources / Accessions that are related to a Classification or Classification Term. There are some Solr queries in the logs, but I'm not familiar enough with the service or how it's implemented in ArchivesSpace to decipher what's going on there.

### Viewing this Order in the DB

```mysql
select 
    cr.resource_id, cr.classification_term_id, cr.aspace_relationship_position, r.identifier, r.title 
from 
    classification_rlshp cr 
    left join resource r on r.id = cr.resource_id
order by 
    cr.classification_term_id,
    cr.aspace_relationship_position;
```

### Viewing this order in the API

```
GET base_url/repositories/:repo_id/classification_terms/:id
GET base_url/repositories/:repo_id/classifications/:id
```

## Possible Solution

I have no idea how this would be fixed. It looks like the ordering of the resources within the is based on the Solr indexes for those resources, which is supported by the Staff interface and PUI each displaying different orderings.

## Steps to Reproduce (for bugs)

1. Create a classification using the Staff Interface
2. Relate a few new resources to the new classification
3. In the staff interface, reorder the resources under the classification
4. Close the record
5. (optional) Clear the search indexes and let them repopulate
6. View the new classification in the PUI and the staff interface. It's possible and likely that these views show different orderings for the resources under that classification, neither being in sync with the explicitly defined ordering.

## Context

I'm migrating some resource data to ArchivesSpace through the API. The data owners have requested that the resources should be linked using the Classifications / Classification Terms modules. Also, they have requested that the resources within the Classifications should be ordered based on their identifiers. It's possible to define this ordering using the API, but the order does not affect the staff and PUI views for the relevant classification terms.

## Your Environment

- ArchivesSpace Version 2.5.0 (Containerized)
- Firefox 62.0.3 (64-bit)

```json
{
    "databaseProductName": "MySQL",
    "databaseProductVersion": "5.7.23",
    "ruby_version": "2.3.0",
    "host_os": "linux",
    "host_cpu": "x86_64",
    "build": "java1.7",
    "archivesSpaceVersion": "v2.5.0"
}
```

**Comment by lorawoodford** [comment] 2020-11-19 20:31
Closing as a near-duplicate of https://archivesspace.atlassian.net/browse/ANW-939.  This retains some useful information, the issue is likely going to get more visibility/discussion within JIRA.

**Closed by lorawoodford** 2020-11-19 20:31 UTC
Labels: JIRA ticket too
