### ISSUE TITLE
Update Tomcat script to remove old JRubies

### ISSUE THREAD

**Issue by quoideneuf** [archivesspace/archivesspace#323] opened 2015-10-20 17:04 UTC
Tomcatters are suffering when we update Jruby because the script leaves around the old jars

:scream:

**Comment by cfitz** [comment] 2015-10-20 17:14
Yeah...but:

1) Its not just jruby, but any other jar.
2) public and frontend are using different jrubies again:
https://github.com/archivesspace/archivesspace/blob/v1.4.1/public/Gemfile.lock#L53
https://github.com/archivesspace/archivesspace/blob/v1.4.1/frontend/Gemfile.lock#L59
3) We probably need to drop Tomcat support...or rather let people kinda do it if they want, but they're on their own?

**Comment by quoideneuf** [comment] 2015-10-20 17:16
I'm sorry about the public JRuby - pretty sure that was me...don't know what to say about Tomcat...

**Comment by bdwestbrook** [comment] 2015-10-21 12:15
RE: no 3, do we need an advisory indicating it is not necessary to use Tomcat to run ASpace, that it can be done on Windows servers without Tomcat?

**Comment by cfitz** [comment] 2015-10-21 12:24
Yes, it might be good to poll folks to see who's using Tomcat. At this
point, its probably fine to keep the script and just give a warning that
this is its own thing.

However, the procrun script ( to setup jetty as a windows service ) is
really untested and is probably still harder for people to do than the TC
setup.

Terry is working on a windows installer, which should do the procrun stuff
for users.

But maybe telling people to use Docker might be better? They've done a lot
of work for windows in the past few months...

We really need some windows help though...

**Comment by pbhenson** [comment] 2015-12-04 23:22
We just deployed archivesspace for our library using tomcat. We run a number of webapps under tomcat and are more familiar with that container. We also want more flexibility and features than the bundled jetty might provide, such as SSL support. We use linux, I don't care about windows support ;).

I'm not clear about the underlying issue here, it's just that an update script isn't doing the right thing?

Thanks...

**Comment by lgsap** [comment] 2015-12-04 23:39
>We probably need to drop Tomcat support...
This seems a bit drastic considering the problem can be fixed in the update script. Can you at least specify why Tomcat support needs to be dropped (especially if there are other issues besides the one described here)?

>We also want more flexibility and features than the bundled jetty might provide, such as SSL support. 
This is why we use Tomcat instead of the embedded Jetty.

Before considering removing Tomcat support, shouldn't the question be brought to the Archivesspace Google Group (or Archivesspace membership)?

**Comment by mark-cooper** [comment] 2015-12-05 02:16
"We also want more flexibility and features than the bundled jetty might provide, such as SSL support. This is why we use Tomcat instead of the embedded Jetty."

Apache or Nginx can be configured to act as a reverse proxy to fulfill this purpose if that is the primary motivation and has the advantage of not requiring additional support from the development team to maintain:

https://github.com/archivesspace/archivesspace/blob/master/README_HTTPS.md

**Comment by cfitz** [comment] 2015-12-05 19:22
@pbhenson  the issue is that there is no update script. And the setup scripts works ok most of the time.

But if people want to use tomcat ( or any other servlet container ), they certainly can. It's pretty straight forward for people who have tomcat experience.  The script was pretty basic...all it did really was copy jar libraries into the classpath and overwrite a config file. It is still avialable here: https://github.com/archivesspace/archivesspace_tomcat for anyone who wants to use it.

The issue is that a lot of Windows users started using Tomcat because it was easier to setup as a windows service. A lot of these organizations lack prior Tomcat experience, and it's been really difficult to help them out when they've run into issue. 

In addition, we can't test again a tomcat setup, which recently burned us when people had unexpected file paths. 

@lgsap if you want to write an update script, that would be great. Just sent a PR to the archivesspace_tomcat repo. Thanks! 

If people want to use Tomcat, they certainly can. If they want to use the script, they certainly can. If they want to ask questions about it on the list, they certainly can.

**Closed** 2015-12-05 19:29 UTC

**Comment by pbhenson** [comment] 2015-12-06 02:12
@mark-cooper Yes, one could use a reverse proxy in front, but that's an extra moving piece that's not really needed; just running it directly in a servlet container with the right feature set is more efficient.

@cfitz Ok, thanks; it wasn't clear if the new position was "Don't use tomcat, it won't work and we won't support it", thanks for the clarification. We didn't actually use the script to deploy our production instance, we just ran it to see what it would do and then replicated it in our packaging and configuration management system. SSL support is one of the main reasons we didn't use the bundled jetty, but we're also a tomcat shop at the moment and have a lot of experience configuring and tuning tomcat.

Ah, those Windows users, they're always causing trouble ;).

**Comment by mark-cooper** [comment] 2015-12-06 02:46
@pbhenson That's cool, just wanted to point out the option is there in case it hadn't been considered.
