### ISSUE TITLE
Spawning Resources from Accessions and  pre-populated fields

### ISSUE THREAD

**Issue by stothert** [archivesspace/archivesspace#1306] opened 2018-07-17 16:15 UTC
We have created a resource template that includes 8 notes that we don't want staff to forget to add to resources. These show up for all users with "Pre-populate Records?" selected in their repository preferences. Unfortunately if you spawn a resource from an accession none of those fields populate.

**Comment by lmcglohon** [comment] 2019-12-16 18:14
Related JIRA tickets - https://archivesspace.atlassian.net/browse/ANW-725 and https://archivesspace.atlassian.net/browse/ANW-616

**Comment by lorawoodford** [comment] 2021-05-05 13:07
Closing as a duplicate of the above mentioned JIRA tickets.

**Closed by lorawoodford** 2021-05-05 13:07 UTC
Labels: JIRA ticket too
